name: pangenome-hgt-sim
channels:
  - conda-forge
  - etetoolkit
  - defaults
dependencies:
  - asttokens=2.4.1
  - attrs=24.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - cairo=1.18.4
  - certifi=2025.7.14
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - daiquiri=3.0.0
  - debugpy=1.8.7
  - decorator=5.1.1
  - demes=0.2.3
  - double-conversion=3.3.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - glib=2.84.2
  - glib-tools=2.84.2
  - graphite2=1.3.13
  - graphviz=13.1.1
  - gsl=2.7
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - gts=0.7.6
  - harfbuzz=11.3.2
  - icu=75.1
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=20.1.8
  - libdeflate=1.22
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgd=2.3.3
  - libglib=2.84.2
  - libhwloc=2.11.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libogg=1.3.5
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsqlite=3.50.3
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - lxml=5.3.0
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mkl=2024.2.2
  - msprime=1.3.1
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numba=0.61.2
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.5.1
  - packaging=24.1
  - pandas=2.2.3
  - pango=1.56.4
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.45
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=23.3.1
  - pixman=0.46.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - ply=3.11
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pygraphviz=1.14
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyside6=6.9.1
  - python=3.12.1
  - python-dateutil=2.9.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.1
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt6-main=6.9.1
  - referencing=0.35.1
  - rpds-py=0.21.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - scipy=1.12.0
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=75.3.0
  - sip=6.7.12
  - six=1.16.0
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - svgwrite=1.4.3
  - tbb=2021.13.0
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.66.1
  - traitlets=5.14.3
  - tskit=0.6.0
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.44.0
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - arviz==0.20.0
      - async-lru==2.0.4
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bintrees==2.2.0
      - biopython==1.85
      - bleach==6.2.0
      - cachetools==5.5.0
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - cloudpickle==3.1.0
      - cons==0.4.6
      - defusedxml==0.7.1
      - ete3==3.0.0b35
      - etuples==0.3.9
      - fastjsonschema==2.20.0
      - filelock==3.16.1
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2024.10.0
      - grpcio==1.67.1
      - h11==0.14.0
      - h5netcdf==1.4.0
      - h5py==3.12.1
      - httpcore==1.0.6
      - httpx==0.27.2
      - idna==3.10
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpickle==4.1.1
      - jsonpointer==3.0.0
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - line-profiler==4.2.0
      - logical-unification==0.4.6
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - minikanren==1.0.3
      - mistune==3.0.2
      - mpmath==1.3.0
      - multidict==6.6.3
      - multipledispatch==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - newick==1.9.0
      - nflows==0.14
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - prometheus-client==0.21.0
      - propcache==0.3.2
      - protobuf==5.28.3
      - pycparser==2.22
      - pydot==4.0.1
      - pyknos==0.16.0
      - pymc==5.18.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytensor==2.25.5
      - pyvis==0.3.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - sbi==0.23.2
      - scikit-learn==1.5.2
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - toolz==1.0.0
      - torch==2.5.1
      - torch-geometric==2.6.1
      - tskit-arg-visualizer==0.0.1
      - types-python-dateutil==2.9.0.20241003
      - uri-template==1.3.0
      - urllib3==2.2.3
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.2
      - widgetsnbextension==4.0.13
      - xarray==2024.10.0
      - xarray-einstats==0.8.0
      - yarl==1.20.1
      - zuko==1.3.0
prefix: C:\Users\uhewm\anaconda3\envs\pangenome-hgt-sim
