name: pangenome-hgt-sim
channels:
  - conda-forge
  - etetoolkit
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.7.14=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.7.14=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py312hd5eb7cc_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - daiquiri=3.0.0=pyhd3deb0d_0
  - debugpy=1.8.7=py312h275cf98_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - demes=0.2.3=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.54.1=py312h31fea79_1
  - freetype=2.13.3=h57928b3_1
  - fribidi=1.0.10=h8d14728_0
  - getopt-win32=0.1=h6a83c73_3
  - glib=2.84.2=he8f994d_0
  - glib-tools=2.84.2=h4394cf3_0
  - graphite2=1.3.13=h63175ca_1003
  - graphviz=13.1.1=ha5e8f4b_0
  - gsl=2.7=hdfb1a43_0
  - gst-plugins-base=1.24.7=hb0a98b8_0
  - gstreamer=1.24.7=h5006eae_0
  - gts=0.7.6=h6b5321d_4
  - harfbuzz=11.3.2=h8796e6f_0
  - icu=75.1=he0c23c2_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.29.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h2e8e312_0
  - kiwisolver=1.4.7=py312hd5eb7cc_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=25_win64_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=25_win64_mkl
  - libclang13=20.1.8=default_hadf22e1_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgd=2.3.3=h7208af6_11
  - libglib=2.84.2=hbc94333_0
  - libhwloc=2.11.1=default_h8125262_1000
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=25_win64_mkl
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.50=h95bef1e_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.3=hf5d6505_1
  - libtiff=4.7.0=hfc51747_1
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.13.8=h442d1da_0
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_2
  - llvmlite=0.44.0=py312h1f7db74_1
  - lxml=5.3.0=py312h53bce91_2
  - m2w64-binutils=2.25.1=5
  - m2w64-bzip2=1.0.6=6
  - m2w64-crt-git=5.0.0.4636.2595836=2
  - m2w64-gcc=5.3.0=6
  - m2w64-gcc-ada=5.3.0=6
  - m2w64-gcc-fortran=5.3.0=6
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gcc-objc=5.3.0=6
  - m2w64-gmp=6.1.0=2
  - m2w64-headers-git=5.0.0.4636.c0ad18a=2
  - m2w64-isl=0.16.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-make=4.1.2351.a80a8b8=2
  - m2w64-mpc=1.0.3=3
  - m2w64-mpfr=3.1.4=4
  - m2w64-pkg-config=0.29.1=2
  - m2w64-toolchain=5.3.0=7
  - m2w64-tools-git=5.0.0.4592.90b8472=2
  - m2w64-windows-default-manifest=6.4=3
  - m2w64-winpthreads-git=5.0.0.4634.697f757=2
  - m2w64-zlib=1.2.8=10
  - matplotlib=3.9.2=py312h2e8e312_2
  - matplotlib-base=3.9.2=py312h90004f6_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2024.2.2=h66d3029_14
  - msprime=1.3.1=py312h67f519c_1
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.4.2=py312haa95532_0
  - numba=0.61.2=py312h5da7b33_0
  - numpy=1.26.4=py312h8753938_0
  - openjpeg=2.5.2=h3d672ee_0
  - openssl=3.5.1=h725018a_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py312h72972c8_1
  - pango=1.56.4=h03d888a_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.45=h99c9b8b_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h381445a_1
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.46.4=hc614b68_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - ply=3.11=py312haa95532_1
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.1.0=py312h4389bb4_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=h2466b09_4
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pygraphviz=1.14=py312h7f62ece_1
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pyqt=5.15.10=py312h5da7b33_1
  - pyqt5-sip=12.13.0=py312h827c3e9_1
  - pyside6=6.9.1=py312h0ba07f7_0
  - python=3.12.1=h2628c8c_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=307=py312h275cf98_3
  - pyzmq=26.2.0=py312hd7027bb_3
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.15=h264fbc2_0
  - qt6-main=6.9.1=h02ddd7d_2
  - referencing=0.35.1=pyhd8ed1ab_0
  - rpds-py=0.21.0=py312h2615798_0
  - ruamel.yaml=0.18.6=py312h4389bb4_1
  - ruamel.yaml.clib=0.2.8=py312h4389bb4_1
  - scipy=1.12.0=py312h8753938_2
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sip=6.7.12=py312h5da7b33_1
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.4=py312h1a27103_0
  - svgwrite=1.4.3=pyhd8ed1ab_0
  - tbb=2021.13.0=hc790b64_0
  - tk=8.6.13=h5226925_1
  - tornado=6.4.1=py312h4389bb4_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - tskit=0.6.0=py312h1a27103_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=15.1.0=py312h4389bb4_1
  - vc=14.3=h8a93ad2_22
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=hcd874cb_1002
  - xorg-libice=1.1.1=hcd874cb_0
  - xorg-libsm=1.2.4=hcd874cb_0
  - xorg-libx11=1.8.9=h0076a8d_1
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xorg-libxext=1.3.4=hcd874cb_2
  - xorg-libxpm=3.5.17=hcd874cb_0
  - xorg-libxt=1.3.0=hcd874cb_1
  - xorg-xextproto=7.3.0=hcd874cb_1003
  - xorg-xproto=7.0.31=hcd874cb_1007
  - xz=5.2.6=h8d14728_0
  - zeromq=4.3.5=ha9f60a1_6
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - arviz==0.20.0
      - async-lru==2.0.4
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bintrees==2.2.0
      - biopython==1.85
      - bleach==6.2.0
      - cachetools==5.5.0
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - cloudpickle==3.1.0
      - cons==0.4.6
      - defusedxml==0.7.1
      - ete3==3.0.0b35
      - etuples==0.3.9
      - fastjsonschema==2.20.0
      - filelock==3.16.1
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2024.10.0
      - grpcio==1.67.1
      - h11==0.14.0
      - h5netcdf==1.4.0
      - h5py==3.12.1
      - httpcore==1.0.6
      - httpx==0.27.2
      - idna==3.10
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpickle==4.1.1
      - jsonpointer==3.0.0
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - line-profiler==4.2.0
      - logical-unification==0.4.6
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - minikanren==1.0.3
      - mistune==3.0.2
      - mpmath==1.3.0
      - multidict==6.6.3
      - multipledispatch==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - newick==1.9.0
      - nflows==0.14
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - prometheus-client==0.21.0
      - propcache==0.3.2
      - protobuf==5.28.3
      - pycparser==2.22
      - pydot==4.0.1
      - pyknos==0.16.0
      - pymc==5.18.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytensor==2.25.5
      - pyvis==0.3.2
      - pywinpty==2.0.14
      - pyyaml==6.0.2
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - sbi==0.23.2
      - scikit-learn==1.5.2
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - toolz==1.0.0
      - torch==2.5.1
      - torch-geometric==2.6.1
      - tskit-arg-visualizer==0.0.1
      - types-python-dateutil==2.9.0.20241003
      - uri-template==1.3.0
      - urllib3==2.2.3
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.2
      - widgetsnbextension==4.0.13
      - xarray==2024.10.0
      - xarray-einstats==0.8.0
      - yarl==1.20.1
      - zuko==1.3.0
prefix: C:\Users\uhewm\anaconda3\envs\pangenome-hgt-sim
